notification/aws/src/main/java/de/taimos/dvalin/notification/push/AmazonSNSPushService.java
=> dvalin-45 Only start PushService when property is present

CHANGELOG.md, interconnect/interconnect-maven-plugin/src/main/resources/ivoIdTemplate.vm, mongodb/src/main/java/de/taimos/dvalin/mongo/AbstractAuditedMongoDAO.java, mongodb/src/main/java/de/taimos/dvalin/mongo/ICrudAuditedDAO.java
- findByIdIVO gets optional version parameter when audited
- auditedDAO gets method to find versioned element
=> enhanced support to get versioned element

CHANGELOG.md, jpa/src/main/java/de/taimos/dvalin/jpa/config/DatabaseConfig.java
Adds a @DependsOn for liquibase to entityManagerFactory, to prevent the bug described in the ticket.
=> A fix for Bugticket #61

interconnect/interconnect-maven-plugin/src/main/java/de/taimos/dvalin/interconnect/model/maven/imports/Imports.java
fixes a potential bug on removing a class from imports
=> fixes a potential bug on removing a class from imports

mongodb/src/main/java/de/taimos/dvalin/mongo/MongoDBDataAccess.java, mongodb/src/test/java/de/taimos/dvalin/mongo/Tester.java
=> Implementation for issue #66

jaxrs/src/main/java/de/taimos/dvalin/jaxrs/providers/AuthorizationProvider.java
Currently, if there is an authentication header set, and the handleAuthHeader returns null, there is no way to abortUnauthorized, without using handleOther.
This leads to situations where you have to do the same Checks twice, just to return an 401 Message.
Example:
handleAuthHeader returns null, if the user has no authorization.
handleOther returns an anonymus user.
If you want bahavior, which either grants an anonym user when no authentication is present, or abortUnauthorized when a authHeader is present but not valid, we would have to check the headers in handleOther again, duplicating the checks (and even doing the whole header to string conversion again).
This change request provides a better solution for problems like the above, while still enabling the current bahviour by simply …
=> Removes fallback in AuthorizationProvider to other if authentication header is set

interconnect/interconnect-maven-plugin/pom.xml
Change to mitigate CVE-2021-29425 in maven
=> fixing template vulnerability

CHANGELOG.md, interconnect/metamodel/pom.xml, interconnect/model/src/main/java/de/taimos/dvalin/interconnect/model/InterconnectConstants.java, interconnect/model/src/main/java/de/taimos/dvalin/interconnect/model/MessageCryptoUtil.java
* Interconnect secury message crypto:
* AES Keys are no longer Hex-encoded but Base64-encoded. This avoids limitation to only 16 characters.
* BREAKING: Changed AES key encoding means potentially a new key is needed (some old keys work, some not)
* Changed AES Block Mode from unsecure ECB to secure GCM
=> Crypto change

CHANGELOG.md, daemon/src/main/java/de/taimos/daemon/properties/CloudConductorPropertyProvider.java
Allow setting https with configuration parameter (before there was only a setter)
=> Cloudconductorpropertyprovider

CHANGELOG.md, jaxrs-jwtauth/pom.xml, jaxrs/pom.xml, pom.xml
* AWS 1.12.163
* Jetty 9.4.45.v20220203
* slf4j 1.7.36
* Nimbus JOSE+JWT 9.20
* Swagger 2.1.13
=> updated dependencies

CHANGELOG.md, interconnect/core/src/it/java/de/taimos/dvalin/interconnect/core/TestHelper.java, interconnect/core/src/main/java/de/taimos/dvalin/interconnect/core/ActiveMQPooledConnectionFactory.java, interconnect/core/src/main/java/de/taimos/dvalin/interconnect/core/DvalinConnectionFactory.java, interconnect/core/src/main/java/de/taimos/dvalin/interconnect/core/MessageConnector.java, interconnect/core/src/main/java/de/taimos/dvalin/interconnect/core/ToTopicSender.java, interconnect/core/src/main/java/de/taimos/dvalin/interconnect/core/config/JMSConfig.java
Optional addition to use authentication with interconnect/ActiveMQ
=> Interconnect auth

CHANGELOG.md, interconnect/model/src/main/java/de/taimos/dvalin/interconnect/model/InterconnectMapper.java
InterconnectMapper: extension to allow registering modules and enabling/disabling features
=> extension of InterconnectMapper

CHANGELOG.md, interconnect/interconnect-maven-plugin/src/main/java/de/taimos/dvalin/interconnect/model/maven/model/ivo/IVOModel.java
Fixing Bug in IVO Generator. Auditing and inheritence resulted in doubled fields(lastChange, lastChangeUser) and strange/unexpected behaviour. Fixed now.
=> ivo generator fix

CHANGELOG.md, interconnect/model/src/main/java/de/taimos/dvalin/interconnect/model/ivo/util/IdWithVersion.java
* Extend IdWithVersion with method toString() for better error logging
=> Extend IdWithVersion

CHANGELOG.md, jpa/dvalin-jpa.iml, pom.xml
Updating Hibernate to Version 5.6.14
=> Updating hibernate

daemon/src/main/java/de/taimos/daemon/log4j/DvalinLog4jConfigurationFactory.java, daemon/src/main/java/de/taimos/daemon/log4j/Log4jDaemonProperties.java, daemon/src/main/java/de/taimos/daemon/log4j/Log4jLoggingConfigurer.java
Fix logger pattern not configurable after log4j update (#103)
=> Fix configurable logger pattern

pom.xml
Bugfix (see https://github.com/mongock/mongock/issues/604)
* **What is the current behavior?** (You can also link to an open issue here)
Mongoc has a problem in combination with the fake mongo config. It ignores the transactions settings and will not work with the face mongo server.
* **What is the new behavior (if this is a feature change)?**
With version 5.2.4 mongoc will respect the transaction settings.
No
* **Other information**:
=> Update mongock to 5.2.4

CHANGELOG.md, daemon/src/main/java/de/taimos/daemon/DaemonStarter.java, interconnect/interconnect-maven-plugin/pom.xml, interconnect/interconnect-maven-plugin/src/main/java/de/taimos/dvalin/interconnect/model/maven/model/ivo/filter/AbstractFindModel.java, interconnect/model/pom.xml, mongodb/pom.xml, pom.xml
* IVO generator: replaced old Apache BeanUtils with Spring beans BeanUtils
* some small additional cleanups
* Better error handling for DaemonStarter.abortSystem
=> IVO generator: replaced old Apache BeanUtils with Spring beans BeanUtils

CHANGELOG.md, interconnect/interconnect-maven-plugin/src/main/resources/event/event.vm, interconnect/interconnect-maven-plugin/src/main/resources/ivo/delete.vm, interconnect/interconnect-maven-plugin/src/main/resources/ivo/find.vm, interconnect/interconnect-maven-plugin/src/main/resources/ivo/findById.vm, interconnect/interconnect-maven-plugin/src/main/resources/ivo/findByIdAudited.vm, interconnect/interconnect-maven-plugin/src/main/resources/ivo/ivo.vm, interconnect/interconnect-maven-plugin/src/main/resources/ivo/modify.vm
Corrects the use of `@Nullable` and `@Nonnull` on generated IVO and Event Classes, especially on the builder part of those.
* **What is the current behavior?** (You can also link to an open issue here)
`@Nullable` and `@Nonnull` are non sensical, not corresponding to the use case
* **What is the new behavior (if this is a feature change)?**
`@Nullable` and `@Nonnull` match the expected behaviour
No
=> corrects @Nullable and @Nonnull annotations on created ivos and events

CHANGELOG.md, jpa/src/main/java/de/taimos/dvalin/jpa/config/H2Config.java
Database support for h2 embedded database.
* **What is the current behavior?** (You can also link to an open issue here)
* **What is the new behavior (if this is a feature change)?**
No
* **Other information**:
=> Add h2 database config

CHANGELOG.md, jaxrs-jwtauth/pom.xml, pom.xml
- [ x] The commit message describes your change
- [ x] Tests for the changes have been added if possible (for bug fixes / features)
- [ x] Docs have been added / updated (for bug fixes / features)
- [ x] Changes are mentioned in the changelog (for bug fixes / features)
Updating dependencies
Fixing vulnerabilities: CVE-2024-29736 (Apache CXF), CVE-2024-38808 (Spring Framework)
No
* **Other information**:
=> updated dependencies, fixing vulnerabilities

.github/workflows/build-maven.yml, interconnect/core/src/main/java/de/taimos/dvalin/interconnect/core/daemon/util/DaemonExceptionMapper.java
Bugfix
* **What is the current behavior?** (You can also link to an open issue here)
After mapping an exception in DaemonExceptionMapper the original exception is used for processing.
* **What is the new behavior (if this is a feature change)?**
After mapping an exception in DaemonExceptionMapper the mapped exception is used for processing.
No
* **Other information**:
=> DaemonExceptionMapper uses mapped exception
